# Generated by Django 2.0.2 on 2020-01-02 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
    ]
